name: Build and smoketest charm

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Create charm package
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out repo
        uses: actions/checkout@v2.3.5
      - name: Install lxd
        run: |
          sudo lxd init --auto
          sudo usermod --append --groups lxd $USER
          sg lxd -c 'lxc version'
          sg lxd -c 'lxc network set lxdbr0 ipv6.address none'
      - name: Install charmcraft
        run: sudo snap install charmcraft
      - name: Build charm
        run: |
          set -x
          cp hacks/lxd-profile.yaml .
          charmcraft build
      - name: Uploading snap
        uses: actions/upload-artifact@v2.2.4
        with:
          name: microk8s.charm
          path: microk8s.charm
      - name: Deploy charm
        run: |
          set -x
          sudo snap install juju --classic
          sudo snap install juju-wait --classic
          sg lxd -c 'juju bootstrap localhost'
          sg lxd -c 'juju deploy ./microk8s.charm --force'
          sg lxd -c 'juju wait -v -t 600'
          sg lxd -c 'juju status'
          sg lxd -c 'juju ssh microk8s/0 microk8s.status --wait-ready -t 600'
          sg lxd -c 'juju ssh microk8s/0 microk8s.kubectl get all -A'
