name: CLA

on:
  pull_request:
    branches: [release-1.28]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@1.2.0
