name: Promote charm

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  test-charm:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3.5.2
      - name: Configure pytest-operator
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          lxd-channel: 5.0/stable
          juju-channel: 3.1/stable
      - name: Add user to lxd group
        run: sudo usermod -a -G lxd $USER
      - name: Install tox
        run: |
          pip3 install tox
      - name: Run integration tests
        run: |
          export MK8S_CHARM_CHANNEL='latest/edge'
          sg lxd -c 'tox -e integration-3.1'
      - name: Retrieve artifacts
        if: always()
        run: |
          mkdir artifacts
          juju debug-log --replay > artifacts/juju.log
          juju status --format yaml > artifacts/juju.yaml
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Logs
          path: artifacts/

  promote-charm:
    needs: test-charm
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    with:
      origin-channel: latest/edge
      destination-channel: latest/edge/promoted
    secrets:
      inherit